name: zones_convolver_tests

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install JUCE's Linux Deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
          version: 1.0
      - uses: lukka/get-cmake@latest
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Run CMake consuming CMakePreset.json
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi'
          cmakeAppendedArgs: '-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
          buildPreset: 'build-release'
          testPreset: 'test-release'